# コース設定ファイル
# 2024年度用の設定

# コース画像設定
image:
  filename: "2025_competition_course_50pct_v0.9.pdf"  # 画像ファイル名
  width: 500  # 画像幅
  height: 730  # 画像高さ
  toriming: 250 # トリミング幅
  scale: 1.0  # スケール倍率

# 座標設定
coordinates:
  origin:
    x: 0  # 原点X座標
    y: 0  # 原点Y座標
  start_line:
    x: 100  # スタートラインX座標
    y: 100  # スタートラインY座標
  goal_line:
    x: 400  # ゴールラインX座標
    y: 600  # ゴールラインY座標

# 色設定
colors:
  black:
    r: 0  # 赤成分
    g: 0  # 緑成分
    b: 0  # 青成分
    brightness: 0  # 明度
  white:
    r: 255  # 赤成分
    g: 255  # 緑成分
    b: 255  # 青成分
    brightness: 70  # 明度

# コースレイアウト設定
layout:
  checkpoints:  # チェックポイント
    - x: 200
      y: 200
    - x: 300
      y: 400
    - x: 400
      y: 500
